language: java
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/wrapper/
jdk:
- oraclejdk8
#deploy:
#  provider: openshift
#  user: luistrigueiros@gmail.com
#  password:
#    secure: NOQylZ4zpf7SADH9OUTCSfqRQ1m1ILdvYUWjbJYJkTSn/JFRyxEkyKiRmmxD0N8PYXVHSKapxnPWyXBRfEeafNBcmtit9nKZc5OXn8RpfxDX6US/dAHB7Gu9luKoVWxSm1K7afLn4d212q2eCbcJoQXcRaeDqV1juMqovlwrsobBZcXJ6apo3Sc7YwP27yQC3mA/FWlFoWqZ0S5gR3ATXkmVhE96qNH0l9lluKJg85Qvdq/qIdC2nSjV5Js6yhziXWhLKRBz4uq46ZI9/jLZ8b3YlCxfp8TVjqJGX3F0KBCCXLnZdCJzg+mzsRxjakwZBfTuY4X0/zG5pPHuSeHEGtdeaOXYeihUClajYO/bCZhuEUGl2RhuPvn/wgLVxUzoPhbqksGjDVIPu0WeaOVMpWxDZFSaf86pK7ATO8lQ/sIemOdOfOwYGn95L7jiSsOFh3BT/FX25JyIjaUTo4avC/FGawx74Z/zRkNdf4HjuVra0/30zNGczN3Msg0v9SQdQxcHO/e6mTOM+MlCF69M/9gvbv8aMqH4Kf5v6y2uTnnbIeyEXO3X2lheVkA1n7R2jSqOKNNAKIdofSpO2zWrPIeCEtdsyrTVInlmUB2o5HD+AbEehQazFVaDvFkNLmZWkIh+zt6yypxf7g26Wq7vK1HSSYB85I3nghtBbhGizWU=
#  app: app
#  domain: southcitychurch
#  on:
#    repo: southcitychurch/scc-web
#